"""
Code export utilities for generating reproducible aeon scripts.
"""

from typing import Any, Dict, List, Optional
import json


class CodeExporter:
    """Generates reproducible Python code snippets for aeon operations."""

    # Import templates by task type
    IMPORTS = {
        "classification": [
            "import numpy as np",
            "from sklearn.model_selection import train_test_split",
            "from sklearn.metrics import accuracy_score, classification_report",
        ],
        "regression": [
            "import numpy as np",
            "from sklearn.model_selection import train_test_split",
            "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score",
        ],
        "clustering": [
            "import numpy as np",
            "from sklearn.metrics import silhouette_score",
        ],
        "forecasting": [
            "import numpy as np",
            "from sklearn.metrics import mean_absolute_error, mean_squared_error",
        ],
        "anomaly_detection": [
            "import numpy as np",
        ],
        "segmentation": [
            "import numpy as np",
        ],
        "transformation": [
            "import numpy as np",
        ],
        "distance": [
            "import numpy as np",
        ],
    }

    def __init__(self):
        """Initialize the code exporter."""
        pass

    def generate_classification_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
        dataset_name: Optional[str] = None,
        test_size: float = 0.2,
        random_state: int = 42,
    ) -> str:
        """Generate classification code snippet."""
        imports = self.IMPORTS["classification"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        if dataset_name:
            imports.append("from aeon.datasets import load_classification")

        # Build params string
        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Classification with {estimator_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
        ]

        # Data loading
        if dataset_name:
            code_lines.extend([
                f"# Load dataset",
                f"X_train, y_train = load_classification('{dataset_name}', split='train')",
                f"X_test, y_test = load_classification('{dataset_name}', split='test')",
                "",
            ])
        else:
            code_lines.extend([
                "# Load your data",
                "# X = ...  # shape: (n_cases, n_channels, n_timepoints)",
                "# y = ...  # labels",
                f"X_train, X_test, y_train, y_test = train_test_split(",
                f"    X, y, test_size={test_size}, random_state={random_state}, stratify=y",
                ")",
                "",
            ])

        # Model
        code_lines.extend([
            "# Create and train classifier",
            f"classifier = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "classifier.fit(X_train, y_train)",
            "",
            "# Predict and evaluate",
            "y_pred = classifier.predict(X_test)",
            "accuracy = accuracy_score(y_test, y_pred)",
            "",
            "print(f'Accuracy: {accuracy:.4f}')",
            "print(classification_report(y_test, y_pred))",
        ])

        return "\n".join(code_lines)

    def generate_regression_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
        dataset_name: Optional[str] = None,
        test_size: float = 0.2,
        random_state: int = 42,
    ) -> str:
        """Generate regression code snippet."""
        imports = self.IMPORTS["regression"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        if dataset_name:
            imports.append("from aeon.datasets import load_regression")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Regression with {estimator_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
        ]

        if dataset_name:
            code_lines.extend([
                f"# Load dataset",
                f"X_train, y_train = load_regression('{dataset_name}', split='train')",
                f"X_test, y_test = load_regression('{dataset_name}', split='test')",
                "",
            ])
        else:
            code_lines.extend([
                "# Load your data",
                "# X = ...  # shape: (n_cases, n_channels, n_timepoints)",
                "# y = ...  # target values",
                f"X_train, X_test, y_train, y_test = train_test_split(",
                f"    X, y, test_size={test_size}, random_state={random_state}",
                ")",
                "",
            ])

        code_lines.extend([
            "# Create and train regressor",
            f"regressor = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "regressor.fit(X_train, y_train)",
            "",
            "# Predict and evaluate",
            "y_pred = regressor.predict(X_test)",
            "",
            "mae = mean_absolute_error(y_test, y_pred)",
            "rmse = np.sqrt(mean_squared_error(y_test, y_pred))",
            "r2 = r2_score(y_test, y_pred)",
            "",
            "print(f'MAE: {mae:.4f}')",
            "print(f'RMSE: {rmse:.4f}')",
            "print(f'R2: {r2:.4f}')",
        ])

        return "\n".join(code_lines)

    def generate_clustering_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
        dataset_name: Optional[str] = None,
    ) -> str:
        """Generate clustering code snippet."""
        imports = self.IMPORTS["clustering"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        if dataset_name:
            imports.append("from aeon.datasets import load_classification")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Clustering with {estimator_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
        ]

        if dataset_name:
            code_lines.extend([
                f"# Load dataset (using labels for evaluation only)",
                f"X, y = load_classification('{dataset_name}')",
                "",
            ])
        else:
            code_lines.extend([
                "# Load your data",
                "# X = ...  # shape: (n_cases, n_channels, n_timepoints)",
                "",
            ])

        code_lines.extend([
            "# Create and fit clusterer",
            f"clusterer = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "cluster_labels = clusterer.fit_predict(X)",
            "",
            "# Evaluate",
            "n_clusters = len(np.unique(cluster_labels))",
            "print(f'Number of clusters: {n_clusters}')",
            "",
            "# Calculate silhouette score",
            "X_flat = X.reshape(X.shape[0], -1)",
            "if n_clusters > 1:",
            "    sil_score = silhouette_score(X_flat, cluster_labels)",
            "    print(f'Silhouette score: {sil_score:.4f}')",
        ])

        return "\n".join(code_lines)

    def generate_forecasting_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
        horizon: int = 10,
    ) -> str:
        """Generate forecasting code snippet."""
        imports = self.IMPORTS["forecasting"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Forecasting with {estimator_name}",
            "# Generated by aeon-play",
            "# Note: Forecasting in aeon is experimental",
            "# " + "=" * 60,
            "",
            *imports,
            "",
            "# Load your time series",
            "# series = ...  # 1D numpy array",
            "",
            "# Split for backtesting",
            f"train = series[:-{horizon}]",
            f"test = series[-{horizon}:]",
            "",
            "# Create and fit forecaster",
            f"forecaster = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "forecaster.fit(train)",
            "",
            "# Forecast",
            f"fh = np.arange(1, {horizon + 1})",
            "forecast = forecaster.predict(fh=fh)",
            "",
            "# Evaluate",
            "mae = mean_absolute_error(test, forecast)",
            "rmse = np.sqrt(mean_squared_error(test, forecast))",
            "",
            "print(f'MAE: {mae:.4f}')",
            "print(f'RMSE: {rmse:.4f}')",
        ])

        return "\n".join(code_lines)

    def generate_anomaly_detection_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
    ) -> str:
        """Generate anomaly detection code snippet."""
        imports = self.IMPORTS["anomaly_detection"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Anomaly Detection with {estimator_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
            "# Load your time series",
            "# series = ...  # shape: (1, 1, n_timepoints) or (1, n_timepoints)",
            "",
            "# Create detector",
            f"detector = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "# Fit and predict",
            "detector.fit(series)",
            "anomaly_scores = detector.predict(series)",
            "",
            "# Find anomalies",
            "anomaly_indices = np.where(anomaly_scores > 0)[0]",
            "print(f'Found {len(anomaly_indices)} anomalous points')",
        ])

        return "\n".join(code_lines)

    def generate_segmentation_code(
        self,
        estimator_name: str,
        estimator_module: str,
        params: Dict[str, Any],
    ) -> str:
        """Generate segmentation code snippet."""
        imports = self.IMPORTS["segmentation"].copy()
        imports.append(f"from {estimator_module} import {estimator_name}")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Segmentation with {estimator_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
            "# Load your time series",
            "# series = ...  # 1D numpy array",
            "",
            "# Create segmenter",
            f"segmenter = {estimator_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "# Fit and find change points",
            "segmenter.fit(series)",
            "change_points = segmenter.predict(series)",
            "",
            "print(f'Found {len(change_points)} change points')",
            "print(f'Change point locations: {change_points}')",
        ])

        return "\n".join(code_lines)

    def generate_transformation_code(
        self,
        transformer_name: str,
        transformer_module: str,
        params: Dict[str, Any],
    ) -> str:
        """Generate transformation code snippet."""
        imports = self.IMPORTS["transformation"].copy()
        imports.append(f"from {transformer_module} import {transformer_name}")

        params_str = self._format_params(params)

        code_lines = [
            "# " + "=" * 60,
            f"# Transformation with {transformer_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *imports,
            "",
            "# Load your data",
            "# X = ...  # shape: (n_cases, n_channels, n_timepoints)",
            "",
            "# Create transformer",
            f"transformer = {transformer_name}(",
            *[f"    {line}" for line in params_str.split("\n") if line.strip()],
            ")",
            "",
            "# Transform",
            "X_transformed = transformer.fit_transform(X)",
            "",
            "print(f'Original shape: {X.shape}')",
            "print(f'Transformed shape: {X_transformed.shape}')",
        ])

        return "\n".join(code_lines)

    def generate_distance_code(
        self,
        distance_name: str,
        params: Dict[str, Any],
    ) -> str:
        """Generate distance computation code snippet."""
        code_lines = [
            "# " + "=" * 60,
            f"# Distance Computation with {distance_name}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            "import numpy as np",
            f"from aeon.distances import {distance_name}_distance",
            "",
            "# Your time series",
            "# series1 = ...  # 1D numpy array",
            "# series2 = ...  # 1D numpy array",
            "",
            "# Compute distance",
        ]

        if params:
            params_str = ", ".join([f"{k}={repr(v)}" for k, v in params.items() if v is not None])
            code_lines.append(f"distance = {distance_name}_distance(series1, series2, {params_str})")
        else:
            code_lines.append(f"distance = {distance_name}_distance(series1, series2)")

        code_lines.extend([
            "",
            "print(f'Distance: {distance:.4f}')",
        ])

        return "\n".join(code_lines)

    def generate_pipeline_code(
        self,
        steps: List[Dict[str, Any]],
        task_type: str,
    ) -> str:
        """Generate pipeline code with multiple steps."""
        imports = set()
        imports.add("import numpy as np")
        imports.add("from sklearn.pipeline import Pipeline")

        pipeline_steps = []

        for i, step in enumerate(steps):
            name = step.get("name", f"step_{i}")
            estimator_name = step.get("estimator")
            estimator_module = step.get("module", "aeon")
            params = step.get("params", {})

            imports.add(f"from {estimator_module} import {estimator_name}")

            params_str = self._format_params(params)
            step_code = f"    ('{name}', {estimator_name}({params_str})),"
            pipeline_steps.append(step_code)

        code_lines = [
            "# " + "=" * 60,
            f"# Pipeline for {task_type}",
            "# Generated by aeon-play",
            "# " + "=" * 60,
            "",
            *sorted(imports),
            "",
            "# Create pipeline",
            "pipeline = Pipeline([",
            *pipeline_steps,
            "])",
            "",
            "# Use the pipeline",
            "# pipeline.fit(X_train, y_train)",
            "# predictions = pipeline.predict(X_test)",
        ])

        return "\n".join(code_lines)

    def _format_params(self, params: Dict[str, Any]) -> str:
        """Format parameters for code generation."""
        if not params:
            return ""

        lines = []
        for key, value in params.items():
            if value is None:
                continue
            if isinstance(value, str):
                lines.append(f"{key}='{value}',")
            elif isinstance(value, (list, dict)):
                lines.append(f"{key}={json.dumps(value)},")
            else:
                lines.append(f"{key}={value},")

        return "\n".join(lines)

    def export_to_file(self, code: str, filename: str) -> bytes:
        """Export code to bytes for download."""
        return code.encode('utf-8')
